import 'key_model.dart';

enum KeyBehaviorType {
  textInsert,
  structureInsert,
  wrapper,
  postfix,
  command,
}

class KeyConfig {
  const KeyConfig._();

  static const List<String> tabs = [
    'Temel',
    'Cebir',
    'Kalkülüs',
    'Kompleks',
    'Lineer Cebir',
  ];

  static const String keyboardLayoutVersion = 'v43-full-keyboard-more-inventory-audit';

  // Compatibility inventory: the numeric/action core is still present and
  // fixed. Runtime rendering uses the premium 8x5 grids below so every tab can
  // expose a symbolic/template surface without changing graph/history logic.
  static const List<List<String?>> basicCoreKeyboard = [
    ['C', '⌫', '%', '÷'],
    ['7', '8', '9', '×'],
    ['4', '5', '6', '−'],
    ['1', '2', '3', '+'],
    ['MORE', '0', '.', 'Ans'],
  ];

  static List<List<String?>> _fixedRowsFor(String activeTab) => [
        ['C', '⌫', '%', '÷', '□/□'],
        ['7', '8', '9', '×', '√□'],
        ['4', '5', '6', '−', '□!'],
        ['1', '2', '3', '+', '|□|'],
        ['MORE', '0', '.', activeTab == 'Temel' ? 'Ans' : '=', '↵'],
      ];

  static const Map<String, List<List<String?>>> premiumSpecialtyRows = {
    'Temel': [
      ['(', ')', 'x', 'y', 'π'],
      ['e', 'sin', 'cos', 'tan', 'ln'],
      ['log', '∞', '□^□', '=', 'n'],
    ],
    'Cebir': [
      ['x', 'y', '{□=□', 'f(□)', 'n'],
      ['a', 'b', 'c', 'π', '□^□'],
      ['(', ')', 'm', 'k', 'e'],
    ],
    'Kalkülüs': [
      ['d/dx', '∫□dx', 'lim', 'Σ', '∞'],
      ['x', 'y', 'dx', 'π', 'e'],
      ['sin', 'cos', 'tan', 'ln', '□^□'],
    ],
    'Kompleks': [
      ['i', 'z', 'Re(□)', 'Im(□)', 'arg(□)'],
      ['z̄', 'θ', 'e^□', 'r', 'π'],
      ['(', ')', '□^□', '□/□', '|□|'],
    ],
    'Lineer Cebir': [
      ['[□ □]', '[□]', 'A', 'B', 'I'],
      ['det(□)', '□⁻¹', '□ᵀ', '□·□', '□×□'],
      ['‖□‖', 'k', '[', ']', ','],
    ],
  };

  static const Map<String, List<String>> longPressMap = {
    '=': ['=', '≠', '<', '>', '≤', '≥', '≈', '≡'],
    'x': ['x', 'x₁', 'x₂', 'x_□'],
    'y': ['y', 'y₁', 'y₂', 'y_□', 'y′', 'y″', 'y‴', 'y⁽□⁾', 'dy/dx', 'd²y/dx²'],
    'z': ['z', 'z₁', 'z₂', 'z̄'],
    'π': ['π', 'e', 'φ'],
    'θ': ['θ', 'rad', 'deg'],
    ',': [',', ';'],
    '√□': ['√□', '∛□', '□√□'],
    '□^□': ['□²', '□³', '□ⁿ', '□⁻¹', '10^□', 'e^□'],
    'sin': ['sin(□)', 'sin⁻¹(□)', 'sinh(□)', 'sinh⁻¹(□)'],
    'cos': ['cos(□)', 'cos⁻¹(□)', 'cosh(□)', 'cosh⁻¹(□)'],
    'tan': ['tan(□)', 'tan⁻¹(□)', 'tanh(□)', 'tanh⁻¹(□)'],
    'ln': ['ln(□)', 'e^□'],
    'log': ['log₁₀(□)', 'log₂(□)', 'log_□(□)'],
    '{□=□': ['{□=□', '{3 denklem', '{n denklem', '{≤ sistem'],
    'f(□)': ['f(□)', 'g(□)', 'h(□)', 'f(□,□)', 'f∘g'],
    '□!': ['□C□', '□P□'],
    'd/dx': ['d/dx(□)', 'd²/dx²(□)', 'd³/dx³(□)', '∂/∂x(□)', '∂²/∂x²(□)'],
    '∫□dx': ['∫□dx', '∫ₐᵇ', '∬', '∭', '∮'],
    'lim': ['lim x→□', 'lim x→∞', 'lim x→0⁺', 'lim x→0⁻'],
    'Σ': ['Σ', 'Π', 'Taylor', 'Maclaurin', 'Geometrik', 'Binom', 'eˣ serisi', 'sin serisi', 'cos serisi', 'ln serisi', 'arctan serisi'],
    'dx': ['dx', 'dy', 'dt', 'dθ'],
    '∞': ['∞', '−∞', '+∞'],
    'i': ['i', '−i', 'i²'],
    'arg(□)': ['arg(□)', 'Arg(□)', 'θ'],
    'z̄': ['z̄', 'Eşlenik'],
    'e^□': ['e^□', 'e^(i□)', 'cis(□)'],
    'r': ['r', 'ρ'],
    '[□ □]': ['2×2', '3×3', '4×4', 'm×n', 'I', '0 matris'],
    '[□]': ['2D vektör', '3D vektör', 'nD vektör', 'satır vektörü', 'sütun vektörü'],
    'A': ['A', 'A₁', 'A₂', 'A⁻¹', 'Aᵀ'],
    'B': ['B', 'B₁', 'B₂', 'B⁻¹', 'Bᵀ'],
    'det(□)': ['det(□)', 'minör', 'kofaktör'],
    '□⁻¹': ['□⁻¹', 'Moore-Penrose'],
    '□ᵀ': ['□ᵀ', '□ᴴ'],
    'I': ['I₂', 'I₃', 'Iₙ', '0 matris'],
    '□·□': ['□·□', 'projeksiyon'],
    '□×□': ['□×□', 'karma çarpım'],
    '‖□‖': ['‖□‖', 'birim vektör', 'mesafe'],
    'k': ['k', 'λ', 'μ'],
  };

  static const Map<String, String> keyInsertTextMap = {
    '÷': '÷',
    '×': '×',
    '−': '-',
    '+': '+',
    '.': '.',
    '%': '%',
    '=': '=',
    '≠': '≠',
    '<': '<',
    '>': '>',
    '≤': '≤',
    '≥': '≥',
    '≈': '≈',
    '≡': '≡',
    'x': 'x',
    'x₁': 'x₁',
    'x₂': 'x₂',
    'xₙ': 'x_□',
    'x_□': 'x_□',
    'y': 'y',
    'y₁': 'y₁',
    'y₂': 'y₂',
    'yₙ': 'y_□',
    'y_□': 'y_□',
    'y′': "y'",
    'y″': "y''",
    'y‴': "y'''",
    'y⁽ⁿ⁾': 'y⁽ⁿ⁾',
    'y⁽□⁾': 'y⁽□⁾',
    'z': 'z',
    'z₁': 'z₁',
    'z₂': 'z₂',
    'z̄': 'z̄',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'n': 'n',
    'r': 'r',
    'ρ': 'ρ',
    'k': 'k',
    'm': 'm',
    'λ': 'λ',
    'μ': 'μ',
    'A': 'A',
    'A₁': 'A₁',
    'A₂': 'A₂',
    'A⁻¹': 'A⁻¹',
    'Aᵀ': 'Aᵀ',
    'B': 'B',
    'B₁': 'B₁',
    'B₂': 'B₂',
    'B⁻¹': 'B⁻¹',
    'Bᵀ': 'Bᵀ',
    'I': 'I',
    'I₂': 'I₂',
    'I₃': 'I₃',
    'Iₙ': 'I_□',
    'I_□': 'I_□',
    'π': 'π',
    'e': 'e',
    'φ': 'φ',
    'i': 'i',
    '−i': '−i',
    'i²': 'i²',
    'θ': 'θ',
    'rad': 'rad',
    'deg': 'deg',
    'dx': 'dx',
    'dy': 'dy',
    'dt': 'dt',
    'dθ': 'dθ',
    '∞': '∞',
    '−∞': '−∞',
    '+∞': '+∞',
    '(': '(',
    ')': ')',
    '[': '[',
    ']': ']',
    ',': ',',
    ';': ';',
    '0': '0',
    '1': '1',
    '2': '2',
    '3': '3',
    '4': '4',
    '5': '5',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9',
    'Kalan': ' mod ',
    'EBOB': 'EBOB(□,□)',
    'EKOK': 'EKOK(□,□)',
    'Asal mı?': 'asal?(□)',
    'İşaret': 'sign(□)',
    '□⁄□': '□⁄□',
    'karışık kesir': '□⁄□',
    'bileşik kesir': '□⁄□',
    'minör': 'minor(□)',
    'kofaktör': 'cofactor(□)',
    'pseudo-inverse': 'pinv(□)',
    'projeksiyon': 'proj(□,□)',
    'Eşlenik': 'conj(□)',
    'Moore-Penrose': 'pinv(□)',
    'karma çarpım': 'triple(□,□,□)',
    'triple product': 'triple(□,□,□)',
    'birim vektör': 'unit(□)',
    'mesafe': 'distance(□,□)',
    '0 matris': '0',
  };

  static const Map<String, KeyBehaviorType> keyBehaviorMap = {
    'C': KeyBehaviorType.command,
    '⌫': KeyBehaviorType.command,
    '↵': KeyBehaviorType.command,
    'MORE': KeyBehaviorType.command,
    'Ans': KeyBehaviorType.command,
    '0': KeyBehaviorType.textInsert,
    '1': KeyBehaviorType.textInsert,
    '2': KeyBehaviorType.textInsert,
    '3': KeyBehaviorType.textInsert,
    '4': KeyBehaviorType.textInsert,
    '5': KeyBehaviorType.textInsert,
    '6': KeyBehaviorType.textInsert,
    '7': KeyBehaviorType.textInsert,
    '8': KeyBehaviorType.textInsert,
    '9': KeyBehaviorType.textInsert,
    '%': KeyBehaviorType.textInsert,
    '÷': KeyBehaviorType.textInsert,
    '×': KeyBehaviorType.textInsert,
    '−': KeyBehaviorType.textInsert,
    '+': KeyBehaviorType.textInsert,
    '.': KeyBehaviorType.textInsert,
    '=': KeyBehaviorType.textInsert,
    '≠': KeyBehaviorType.textInsert,
    '<': KeyBehaviorType.textInsert,
    '>': KeyBehaviorType.textInsert,
    '≤': KeyBehaviorType.textInsert,
    '≥': KeyBehaviorType.textInsert,
    '≈': KeyBehaviorType.textInsert,
    '≡': KeyBehaviorType.textInsert,
    'x': KeyBehaviorType.textInsert,
    'x₁': KeyBehaviorType.textInsert,
    'x₂': KeyBehaviorType.textInsert,
    'xₙ': KeyBehaviorType.structureInsert,
    'x_□': KeyBehaviorType.structureInsert,
    'y': KeyBehaviorType.textInsert,
    'y₁': KeyBehaviorType.textInsert,
    'y₂': KeyBehaviorType.textInsert,
    'yₙ': KeyBehaviorType.structureInsert,
    'y_□': KeyBehaviorType.structureInsert,
    'y′': KeyBehaviorType.textInsert,
    'y″': KeyBehaviorType.textInsert,
    'y‴': KeyBehaviorType.textInsert,
    'y⁽ⁿ⁾': KeyBehaviorType.textInsert,
    'y⁽□⁾': KeyBehaviorType.structureInsert,
    'z': KeyBehaviorType.textInsert,
    'z₁': KeyBehaviorType.textInsert,
    'z₂': KeyBehaviorType.textInsert,
    'z̄': KeyBehaviorType.textInsert,
    'a': KeyBehaviorType.textInsert,
    'b': KeyBehaviorType.textInsert,
    'c': KeyBehaviorType.textInsert,
    'n': KeyBehaviorType.textInsert,
    'r': KeyBehaviorType.textInsert,
    'ρ': KeyBehaviorType.textInsert,
    'k': KeyBehaviorType.textInsert,
    'm': KeyBehaviorType.textInsert,
    'λ': KeyBehaviorType.textInsert,
    'μ': KeyBehaviorType.textInsert,
    'A': KeyBehaviorType.textInsert,
    'A₁': KeyBehaviorType.textInsert,
    'A₂': KeyBehaviorType.textInsert,
    'A⁻¹': KeyBehaviorType.textInsert,
    'Aᵀ': KeyBehaviorType.textInsert,
    'B': KeyBehaviorType.textInsert,
    'B₁': KeyBehaviorType.textInsert,
    'B₂': KeyBehaviorType.textInsert,
    'B⁻¹': KeyBehaviorType.textInsert,
    'Bᵀ': KeyBehaviorType.textInsert,
    'I': KeyBehaviorType.textInsert,
    'I₂': KeyBehaviorType.textInsert,
    'I₃': KeyBehaviorType.textInsert,
    'Iₙ': KeyBehaviorType.structureInsert,
    'I_□': KeyBehaviorType.structureInsert,
    'π': KeyBehaviorType.textInsert,
    'e': KeyBehaviorType.textInsert,
    'φ': KeyBehaviorType.textInsert,
    'i': KeyBehaviorType.textInsert,
    '−i': KeyBehaviorType.textInsert,
    'i²': KeyBehaviorType.textInsert,
    'θ': KeyBehaviorType.textInsert,
    'rad': KeyBehaviorType.textInsert,
    'deg': KeyBehaviorType.textInsert,
    'dx': KeyBehaviorType.textInsert,
    'dy': KeyBehaviorType.textInsert,
    'dt': KeyBehaviorType.textInsert,
    'dθ': KeyBehaviorType.textInsert,
    '∞': KeyBehaviorType.textInsert,
    '−∞': KeyBehaviorType.textInsert,
    '+∞': KeyBehaviorType.textInsert,
    '(': KeyBehaviorType.textInsert,
    ')': KeyBehaviorType.textInsert,
    '[': KeyBehaviorType.textInsert,
    ']': KeyBehaviorType.textInsert,
    ',': KeyBehaviorType.textInsert,
    ';': KeyBehaviorType.textInsert,
    'Kalan': KeyBehaviorType.textInsert,
    'karışık kesir': KeyBehaviorType.structureInsert,
    'bileşik kesir': KeyBehaviorType.structureInsert,
    'EBOB': KeyBehaviorType.structureInsert,
    'EKOK': KeyBehaviorType.structureInsert,
    'Asal mı?': KeyBehaviorType.structureInsert,
    'İşaret': KeyBehaviorType.structureInsert,
    '□/□': KeyBehaviorType.structureInsert,
    '□⁄□': KeyBehaviorType.structureInsert,
    '√□': KeyBehaviorType.structureInsert,
    '³√': KeyBehaviorType.structureInsert,
    'ⁿ√': KeyBehaviorType.structureInsert,
    '∛□': KeyBehaviorType.structureInsert,
    '□√□': KeyBehaviorType.structureInsert,
    '□^□': KeyBehaviorType.structureInsert,
    '□²': KeyBehaviorType.structureInsert,
    '□³': KeyBehaviorType.structureInsert,
    '□ⁿ': KeyBehaviorType.structureInsert,
    '10^□': KeyBehaviorType.structureInsert,
    'e^□': KeyBehaviorType.structureInsert,
    '|□|': KeyBehaviorType.wrapper,
    '⌊□⌋': KeyBehaviorType.structureInsert,
    '⌈□⌉': KeyBehaviorType.structureInsert,
    'sin': KeyBehaviorType.structureInsert,
    'sin(□)': KeyBehaviorType.structureInsert,
    'asin(□)': KeyBehaviorType.structureInsert,
    'sin⁻¹(□)': KeyBehaviorType.structureInsert,
    'sinh(□)': KeyBehaviorType.structureInsert,
    'asinh(□)': KeyBehaviorType.structureInsert,
    'sinh⁻¹(□)': KeyBehaviorType.structureInsert,
    'cos': KeyBehaviorType.structureInsert,
    'cos(□)': KeyBehaviorType.structureInsert,
    'acos(□)': KeyBehaviorType.structureInsert,
    'cos⁻¹(□)': KeyBehaviorType.structureInsert,
    'cosh(□)': KeyBehaviorType.structureInsert,
    'acosh(□)': KeyBehaviorType.structureInsert,
    'cosh⁻¹(□)': KeyBehaviorType.structureInsert,
    'tan': KeyBehaviorType.structureInsert,
    'tan(□)': KeyBehaviorType.structureInsert,
    'atan(□)': KeyBehaviorType.structureInsert,
    'tan⁻¹(□)': KeyBehaviorType.structureInsert,
    'tanh(□)': KeyBehaviorType.structureInsert,
    'atanh(□)': KeyBehaviorType.structureInsert,
    'tanh⁻¹(□)': KeyBehaviorType.structureInsert,
    'cot': KeyBehaviorType.structureInsert,
    'cot(□)': KeyBehaviorType.structureInsert,
    'acot': KeyBehaviorType.structureInsert,
    'acot(□)': KeyBehaviorType.structureInsert,
    'cot⁻¹(□)': KeyBehaviorType.structureInsert,
    'coth': KeyBehaviorType.structureInsert,
    'coth(□)': KeyBehaviorType.structureInsert,
    'sec': KeyBehaviorType.structureInsert,
    'sec(□)': KeyBehaviorType.structureInsert,
    'csc': KeyBehaviorType.structureInsert,
    'csc(□)': KeyBehaviorType.structureInsert,
    'ln': KeyBehaviorType.structureInsert,
    'ln(□)': KeyBehaviorType.structureInsert,
    'log': KeyBehaviorType.structureInsert,
    'log(□)': KeyBehaviorType.structureInsert,
    'log₁₀(□)': KeyBehaviorType.structureInsert,
    'log₂(□)': KeyBehaviorType.structureInsert,
    'log_□(□)': KeyBehaviorType.structureInsert,
    '{□=□': KeyBehaviorType.structureInsert,
    '{3 denklem': KeyBehaviorType.structureInsert,
    '{n denklem': KeyBehaviorType.structureInsert,
    '{≤ sistem': KeyBehaviorType.structureInsert,
    'f(□)': KeyBehaviorType.structureInsert,
    'g(□)': KeyBehaviorType.structureInsert,
    'h(□)': KeyBehaviorType.structureInsert,
    'f(□,□)': KeyBehaviorType.structureInsert,
    'f∘g': KeyBehaviorType.structureInsert,
    '□!': KeyBehaviorType.postfix,
    '□P□': KeyBehaviorType.structureInsert,
    '□C□': KeyBehaviorType.structureInsert,
    'Γ(□)': KeyBehaviorType.structureInsert,
    'd/dx': KeyBehaviorType.structureInsert,
    'd/dx(□)': KeyBehaviorType.structureInsert,
    'd²/dx²(□)': KeyBehaviorType.structureInsert,
    'd³/dx³(□)': KeyBehaviorType.structureInsert,
    '∂/∂x(□)': KeyBehaviorType.structureInsert,
    '∂²/∂x²(□)': KeyBehaviorType.structureInsert,
    'dy/dx': KeyBehaviorType.structureInsert,
    'd²y/dx²': KeyBehaviorType.structureInsert,
    '∫□dx': KeyBehaviorType.structureInsert,
    '∫ₐᵇ': KeyBehaviorType.structureInsert,
    '∬': KeyBehaviorType.structureInsert,
    '∭': KeyBehaviorType.structureInsert,
    '∮': KeyBehaviorType.structureInsert,
    'lim': KeyBehaviorType.structureInsert,
    'lim x→□': KeyBehaviorType.structureInsert,
    'lim x→∞': KeyBehaviorType.structureInsert,
    'lim x→0⁺': KeyBehaviorType.structureInsert,
    'lim x→0⁻': KeyBehaviorType.structureInsert,
    'Σ': KeyBehaviorType.structureInsert,
    'Π': KeyBehaviorType.structureInsert,
    'Taylor': KeyBehaviorType.structureInsert,
    'Maclaurin': KeyBehaviorType.structureInsert,
    'Geometrik': KeyBehaviorType.structureInsert,
    'Binom': KeyBehaviorType.structureInsert,
    'eˣ serisi': KeyBehaviorType.structureInsert,
    'sin serisi': KeyBehaviorType.structureInsert,
    'cos serisi': KeyBehaviorType.structureInsert,
    'ln serisi': KeyBehaviorType.structureInsert,
    'arctan serisi': KeyBehaviorType.structureInsert,
    'Re(□)': KeyBehaviorType.structureInsert,
    'real(□)': KeyBehaviorType.structureInsert,
    'Im(□)': KeyBehaviorType.structureInsert,
    'imag(□)': KeyBehaviorType.structureInsert,
    'arg(□)': KeyBehaviorType.structureInsert,
    'Arg(□)': KeyBehaviorType.structureInsert,
    'conj(□)': KeyBehaviorType.structureInsert,
    'Eşlenik': KeyBehaviorType.structureInsert,
    'cis(□)': KeyBehaviorType.structureInsert,
    'e^(i□)': KeyBehaviorType.structureInsert,
    '[□ □]': KeyBehaviorType.structureInsert,
    '[□]': KeyBehaviorType.structureInsert,
    '2×2': KeyBehaviorType.structureInsert,
    '3×3': KeyBehaviorType.structureInsert,
    '4×4': KeyBehaviorType.structureInsert,
    'm×n': KeyBehaviorType.structureInsert,
    '0 matris': KeyBehaviorType.structureInsert,
    '2D vektör': KeyBehaviorType.structureInsert,
    '3D vektör': KeyBehaviorType.structureInsert,
    'nD vektör': KeyBehaviorType.structureInsert,
    'satır vektörü': KeyBehaviorType.structureInsert,
    'sütun vektörü': KeyBehaviorType.structureInsert,
    'det(□)': KeyBehaviorType.structureInsert,
    'minör': KeyBehaviorType.structureInsert,
    'kofaktör': KeyBehaviorType.structureInsert,
    '□⁻¹': KeyBehaviorType.postfix,
    'pseudo-inverse': KeyBehaviorType.structureInsert,
    'Moore-Penrose': KeyBehaviorType.structureInsert,
    '□ᵀ': KeyBehaviorType.postfix,
    '□ᴴ': KeyBehaviorType.postfix,
    '□·□': KeyBehaviorType.structureInsert,
    'dot(□,□)': KeyBehaviorType.structureInsert,
    'projeksiyon': KeyBehaviorType.structureInsert,
    '□×□': KeyBehaviorType.structureInsert,
    'cross(□,□)': KeyBehaviorType.structureInsert,
    'triple product': KeyBehaviorType.structureInsert,
    'karma çarpım': KeyBehaviorType.structureInsert,
    '‖□‖': KeyBehaviorType.wrapper,
    'birim vektör': KeyBehaviorType.structureInsert,
    'mesafe': KeyBehaviorType.structureInsert,
  };

  static KeyBehaviorType getKeyBehavior(String label) {
    return keyBehaviorMap[label] ?? KeyBehaviorType.textInsert;
  }

  static String getInsertText(String label) {
    return keyInsertTextMap[label] ?? label;
  }

  static KeyboardSections buildKeyboardSections(String activeTab) {
    final specialty = premiumSpecialtyRows[activeTab] ?? premiumSpecialtyRows['Temel']!;
    final rows = <List<String?>>[
      ...specialty,
      ..._fixedRowsFor(activeTab),
    ];
    return KeyboardSections.expanded(_toCells(rows));
  }

  static bool hasLongPressOptions(String label, String activeTab) {
    return getLongPressOptions(label, activeTab).isNotEmpty;
  }

  static List<String> getLongPressOptions(String label, String activeTab) {
    final rawOptions = longPressMap[label] ?? const <String>[];

    // Keep frozen regression contracts intact: several keys intentionally expose
    // their primary mathematical form as the first long-press option so tests and
    // muscle memory can lock the popup envelope. Only remove exact duplicates
    // after their first occurrence; do not remove the first option merely because
    // it equals the key label.
    final seen = <String>{};
    final options = <String>[];
    for (final option in rawOptions) {
      if (seen.add(option)) {
        options.add(option);
      }
    }

    if (activeTab == 'Cebir' && label == '∫□dx') {
      return options.where((option) => option != '∬' && option != '∭' && option != '∮').toList(growable: false);
    }
    return List<String>.unmodifiable(options);
  }

  static List<List<MathKeyCell>> _toCells(List<List<String?>> rows) {
    return rows.map((row) => row.map((label) => MathKeyCell(label)).toList(growable: false)).toList(growable: false);
  }
}
